
export const MEDICATION_STORAGE_KEY = 'medications_data';
export const BLOOD_PRESSURE_STORAGE_KEY = 'blood_pressure_data';
export const LANGUAGE_STORAGE_KEY = 'app_language';

export const translations = {
    es: {
        languageName: "español",
        home: "Inicio",
        medications: "Medicamentos",
        bloodPressure: "Tensión Arterial",
        history: "Historial",
        suggestions: "Sugerencias",
        aboutApp: "Ajustes",
        howToUseApp: "Guía de Uso",
        back: "Volver",
        appTitle: "Salud Fácil",
        appSubtitle: "Tu asistente personal para el control de medicinas y tensión arterial.",
        yourMedications: "Tus Medicamentos",
        addMedication: "Añadir Medicamento",
        editMedication: "Editar Medicamento",
        markAsTaken: "Marcar como tomado",
        medicationTaken: "Tomado",
        noMedications: "No hay medicamentos registrados. ¡Añade uno!",
        medicationName: "Nombre del Medicamento:",
        dosage: "Dosis (ej. 500mg, 1 pastilla):",
        frequency: "Frecuencia:",
        daily: "Diario",
        weekly: "Semanal",
        specificTime: "Horas específicas",
        withMeals: "Con las comidas",
        mealTimes: "Momento de la comida:",
        breakfast: "Desayuno",
        lunch: "Almuerzo",
        dinner: "Cena",
        daysOfWeek: "Días de la semana:",
        sunday: "Domingo",
        monday: "Lunes",
        tuesday: "Martes",
        wednesday: "Miércoles",
        thursday: "Jueves",
        friday: "Viernes",
        saturday: "Sábado",
        times: "Horas:",
        addAnotherTime: "Añadir otra hora",
        saveMedication: "Guardar Medicamento",
        updateMedication: "Actualizar Medicamento",
        cancel: "Cancelar",
        bloodPressureLog: "Registro de Tensión Arterial",
        addReading: "Añadir Lectura",
        editReading: "Editar Lectura de Tensión",
        systolic: "Sistólica (mmHg):",
        diastolic: "Diastólica (mmHg):",
        pulse: "Pulso (bpm):",
        notesOptional: "Notas (opcional):",
        setReminder: "Establecer recordatorio para tomar tensión:",
        reminderTime: "Hora del recordatorio:",
        reminderDays: "Días del recordatorio:",
        saveReading: "Guardar Lectura",
        updateReading: "Actualizar Lectura",
        bloodPressureChart: "Gráfico de Tensión Arterial",
        systolicShort: "Sistólica",
        diastolicShort: "Diastólica",
        pulseShort: "Pulsaciones",
        needMoreReadings: "Necesitas al menos 2 lecturas para ver el gráfico.",
        noReadings: "No hay lecturas de tensión. ¡Añade una!",
        fullHistory: "Historial Completo",
        exportHistory: "Exportar Historial a CSV",
        noHistory: "No hay eventos en el historial.",
        medicationEvent: "Medicamento: {name} ({dosage}) - Tomado",
        bpEvent: "Tensión: {systolic}/{diastolic} mmHg, Pulso: {pulse} bpm - {time}",
        confirmDeleteMedication: "¿Estás seguro de que quieres eliminar este medicamento?",
        medicationDeleted: "Medicamento eliminado.",
        confirmDeleteReading: "¿Estás seguro de que quieres eliminar esta lectura?",
        readingDeleted: "Lectura eliminada.",
        fillAllFields: "Por favor, rellena todos los campos obligatorios.",
        selectAtLeastOneDay: "Por favor, selecciona al menos un día para la frecuencia semanal.",
        enterAllTimes: "Por favor, introduce todas las horas para la frecuencia específica.",
        selectMealTime: "Por favor, selecciona al menos un momento de comida.",
        medicationAddedSuccess: "¡Medicamento añadido con éxito!",
        medicationUpdatedSuccess: "¡Medicamento actualizado con éxito!",
        bpReadingAddedSuccess: "¡Tensión arterial registrada con éxito!",
        bpReadingUpdatedSuccess: "¡Tensión arterial actualizada con éxito!",
        dataLoadError: "No se pudo cargar la información guardada. Se ha reiniciado la aplicación.",
        exportSuccess: "Historial exportado a historial_salud_facil.csv",
        installTitle: "Instala la App en tu Teléfono (PWA)",
        installStep1: "1. Abre el enlace de la aplicación en tu navegador (Chrome, Safari, etc.).",
        installStep2: "2. Busca el icono de 'Compartir' o el menú de tu navegador (normalmente tres puntos).",
        installStep3: "3. Selecciona la opción 'Añadir a pantalla de inicio' o 'Instalar aplicación'.",
        installStep4: "4. Confirma la instalación. El icono de 'Salud Fácil' aparecerá en tu pantalla de inicio.",
        installStep5: "5. ¡Listo! Ahora puedes usar la app como una aplicación nativa.",
        securityWarningTitle: "¡Tu Privacidad es Nuestra Prioridad!",
        securityWarningText1: "Es posible que tu teléfono o navegador muestre advertencias al instalar. Esto es NORMAL para una 'Web App Progresiva' (PWA) que no proviene de una tienda de aplicaciones.",
        securityWarningText2: "Te garantizamos que la aplicación es **COMPLETAMENTE SEGURA**.",
        securityWarningText3: "Tus datos se guardan ÚNICAMENTE en tu teléfono y NUNCA salen de él.",
        securityPoint1: "•  **Datos 100% Locales:** La aplicación NO se conecta a ningún servidor externo. Tus datos son solo tuyos.",
        securityPoint2: "•  **Sin Recopilación de Datos:** Esta aplicación no recopila, almacena ni comparte ningún tipo de dato personal.",
        securityPoint3: "•  **Código Abierto:** El código es visible y auditable para total transparencia.",
        securityPoint4: "•  **Contacto Directo:** Para cualquier duda, contacta al desarrollador: Guillermo Pérez (coachdeeper@gmail.com).",
        suggestionsTitle: "Envía tus Sugerencias",
        suggestionsSubtitle: "Tu opinión es muy importante para mejorar la app.",
        suggestionSubject: "Asunto:",
        suggestionMessage: "Tu sugerencia:",
        sendSuggestion: "Enviar Sugerencia",
        emailClientWillOpen: "Se abrirá tu cliente de correo para enviar la sugerencia.",
        aboutTitle: "Ajustes y Copyright",
        copyrightText: "Esta app es propiedad intelectual de Guillermo Pérez (CoachDeeper). Prohibida su copia, modificación o distribución sin autorización expresa. Contacto: coachdeeper@gmail.com.",
        emailContact: "coachdeeper@gmail.com",
        itIsTimeToTakeMedication: "¡Hora de tomar tu medicamento!",
        accept: "Aceptar",
        removeTime: "Eliminar",
        howToUseHome: "Navega a las secciones clave: 'Medicamentos', 'Tensión Arterial' e 'Historial'.",
        howToUseMedications: "Añade, edita y marca tus medicamentos como tomados. Configura dosis y frecuencias personalizadas.",
        howToUseBloodPressure: "Registra tus lecturas de tensión. La app generará un gráfico visual para seguir tu progreso.",
        howToUseHistory: "Revisa un resumen cronológico de todas tus tomas y lecturas. Exporta tu historial a CSV.",
        howToUseSuggestions: "Envíanos tus sugerencias para mejorar la aplicación a través de tu cliente de correo.",
        howToUseAbout: "Información sobre la autoría, derechos de la app y opciones de copia de seguridad.",
        deleteMedication: "Eliminar Medicamento",
        deleteReading: "Eliminar Lectura",
        date: "Fecha",
        notes: "Notas",
        dosesForToday: "Dosis para hoy:",
        noDosesForToday: "No hay dosis programadas para hoy.",
        notificationsNotSupported: "Tu navegador no soporta notificaciones.",
        notificationsDenied: "Has denegado los permisos de notificación. Por favor, actívalos en la configuración de tu navegador si deseas recordatorios.",
        bpReminderTitle: "Recordatorio de Tensión Arterial",
        bpReminderBody: "Es hora de tomar tu lectura de tensión arterial.",
        backupAndRestore: "Copia de Seguridad y Restauración",
        backupDescription: "Guarda una copia de seguridad de todos tus datos en un archivo. Podrás restaurarla más tarde o en otro dispositivo.",
        createBackup: "Crear Copia de Seguridad",
        restoreFromBackup: "Restaurar desde Copia",
        backupSuccess: "¡Copia de seguridad creada con éxito!",
        backupFailed: "Error al crear la copia de seguridad.",
        confirmRestore: "¿Estás seguro de que quieres restaurar los datos? Todos los datos actuales se sobrescribirán.",
        restoreSuccess: "¡Datos restaurados con éxito! La aplicación se recargará.",
        restoreFailed: "Error al restaurar los datos. El archivo puede estar dañado.",
        restoreInvalidFile: "El archivo de copia de seguridad no es válido.",
        searchHistory: "Buscar en el historial...",
        noResultsFound: "No se encontraron resultados.",
        guideWelcomeTitle: "¡Bienvenido/a a Salud Fácil!",
        guideWelcomeText: "Esta guía te ayudará a sacarle el máximo partido a tu asistente de salud personal. Toda tu información es privada y se guarda solo en tu dispositivo.",
        guideFeaturesTitle: "Funcionalidades Principales",
        guideFeatureMeds: "**Gestión de Medicamentos:** Añade todos tus medicamentos, personaliza las dosis, horarios, y frecuencias (diaria, semanal, con comidas). Marca cada toma para no olvidarte de ninguna.",
        guideFeatureBP: "**Control de Tensión Arterial:** Registra tus lecturas de tensión (sistólica, diastólica) y pulso. Visualiza tu progreso con un gráfico interactivo.",
        guideFeatureHistory: "**Historial Completo:** Consulta un registro cronológico de cada medicamento tomado y cada lectura de tensión. ¡Puedes buscar y exportar tu historial!",
        guideFeatureBackup: "**Copias de Seguridad:** No pierdas tus datos. Desde 'Ajustes', puedes crear una copia de seguridad de toda tu información y restaurarla cuando lo necesites.",
        guideExamplesTitle: "Ejemplos Prácticos",
        guideExampleMedsTitle: "Caso 1: Tratamiento Diario y Semanal",
        guideExampleMedsText: "Imagina que tomas 'Fármaco A' cada día a las 9:00 y 'Vitamina D' solo los domingos. Configura ambos en la sección 'Medicamentos'. La app te mostrará cada día qué te toca y podrás marcarlo como 'Tomado' para llevar un control perfecto.",
        guideExampleBPTitle: "Caso 2: Seguimiento para el Médico",
        guideExampleBPText: "Tu médico te pide que te tomes la tensión dos veces al día. Registra cada lectura en 'Tensión Arterial'. Cuando vayas a consulta, podrás mostrarle el gráfico interactivo directamente desde tu móvil o usar el botón 'Exportar' en el 'Historial' para enviárselo por correo.",
        guideProTipsTitle: "Consejos para Sacarle el Máximo Partido",
        guideProTip1: "**Instala la App:** Sigue los pasos de instalación para tener 'Salud Fácil' en tu pantalla de inicio. Funciona sin internet y es más cómodo.",
        guideProTip2: "**Activa Recordatorios:** Cuando configures un medicamento o una lectura de tensión, establece un horario para recibir una notificación. Es la forma más eficaz de no olvidar nada.",
        guideProTip3: "**Usa las Notas:** Al registrar una lectura de tensión, ¿te sentías mareado? ¿Habías hecho ejercicio? Anótalo en 'Notas'. Es información muy valiosa para ti y para tu médico.",
        guideProTip4: "**Haz Copias de Seguridad:** Especialmente si vas a cambiar de teléfono. Ve a 'Ajustes' y crea una copia de seguridad de vez en cuando. ¡Es tu seguro de datos!",
        analyzeWithAI: "Analizar con IA",
        aiAnalysisTitle: "Análisis de IA",
        aiAnalysisLoading: "Analizando tus datos...",
        aiAnalysisDisclaimer: "Este es un análisis generado por IA y no sustituye el consejo médico profesional.",
        aiAnalysisError: "No se pudo completar el análisis. Por favor, inténtalo de nuevo.",
        needMoreReadingsForAI: "Se necesitan al menos 5 lecturas para un análisis significativo.",
    },
    it: {
        languageName: "italiano",
        home: "Home",
        medications: "Farmaci",
        bloodPressure: "Pressione",
        history: "Cronologia",
        suggestions: "Suggerimenti",
        aboutApp: "Impostazioni",
        howToUseApp: "Guida",
        back: "Indietro",
        appTitle: "Salute Facile",
        appSubtitle: "Il tuo assistente personale per farmaci e pressione.",
        yourMedications: "I tuoi Farmaci",
        addMedication: "Aggiungi Farmaco",
        editMedication: "Modifica Farmaco",
        markAsTaken: "Segna assunto",
        medicationTaken: "Assunto",
        noMedications: "Nessun farmaco. Aggiungine uno!",
        medicationName: "Nome Farmaco:",
        dosage: "Dosaggio (es. 500mg):",
        frequency: "Frequenza:",
        daily: "Quotidiana",
        weekly: "Settimanale",
        specificTime: "Orari specifici",
        withMeals: "Con i pasti",
        mealTimes: "Pasto:",
        breakfast: "Colazione",
        lunch: "Pranzo",
        dinner: "Cena",
        daysOfWeek: "Giorni della settimana:",
        sunday: "Domenica",
        monday: "Lunedì",
        tuesday: "Martedì",
        wednesday: "Mercoledì",
        thursday: "Giovedì",
        friday: "Venerdì",
        saturday: "Sabato",
        times: "Orari:",
        addAnotherTime: "Aggiungi orario",
        saveMedication: "Salva Farmaco",
        updateMedication: "Aggiorna Farmaco",
        cancel: "Annulla",
        bloodPressureLog: "Registro Pressione",
        addReading: "Aggiungi Lettura",
        editReading: "Modifica Lettura",
        systolic: "Sistolica (mmHg):",
        diastolic: "Diastolica (mmHg):",
        pulse: "Pulsazioni (bpm):",
        notesOptional: "Note (opzionale):",
        setReminder: "Imposta promemoria pressione:",
        reminderTime: "Ora promemoria:",
        reminderDays: "Giorni promemoria:",
        saveReading: "Salva Lettura",
        updateReading: "Aggiorna Lettura",
        bloodPressureChart: "Grafico Pressione",
        systolicShort: "Sistolica",
        diastolicShort: "Diastolica",
        pulseShort: "Pulsazioni",
        needMoreReadings: "Servono almeno 2 letture per il grafico.",
        noReadings: "Nessuna lettura. Aggiungine una!",
        fullHistory: "Cronologia Completa",
        exportHistory: "Esporta Cronologia in CSV",
        noHistory: "Nessun evento nella cronologia.",
        medicationEvent: "Farmaco: {name} ({dosage}) - Assunto",
        bpEvent: "Pressione: {systolic}/{diastolic} mmHg, Pulsazioni: {pulse} bpm - {time}",
        confirmDeleteMedication: "Sei sicuro di voler eliminare questo farmaco?",
        medicationDeleted: "Farmaco eliminato.",
        confirmDeleteReading: "Sei sicuro di voler eliminare questa lettura?",
        readingDeleted: "Lettura eliminata.",
        fillAllFields: "Compila tutti i campi obbligatori.",
        selectAtLeastOneDay: "Seleziona almeno un giorno.",
        enterAllTimes: "Inserisci tutti gli orari.",
        selectMealTime: "Seleziona almeno un pasto.",
        medicationAddedSuccess: "Farmaco aggiunto!",
        medicationUpdatedSuccess: "Farmaco aggiornato!",
        bpReadingAddedSuccess: "Lettura registrata!",
        bpReadingUpdatedSuccess: "Lettura aggiornata!",
        dataLoadError: "Impossibile caricare i dati. L'app è stata ripristinata.",
        exportSuccess: "Cronologia esportata con successo.",
        installTitle: "Installa l'App sul tuo Telefono (PWA)",
        installStep1: "1. Apri il link dell'app nel tuo browser.",
        installStep2: "2. Cerca l'icona 'Condividi' o il menu del browser.",
        installStep3: "3. Seleziona 'Aggiungi a schermata iniziale' o 'Installa app'.",
        installStep4: "4. Conferma. L'icona apparirà sulla tua home.",
        installStep5: "5. Fatto! Usala come un'app nativa.",
        securityWarningTitle: "La Tua Privacy è la Nostra Priorità!",
        securityWarningText1: "Potresti vedere avvisi durante l'installazione. È NORMALE per le PWA non provenienti da app store.",
        securityWarningText2: "Garantiamo che l'applicazione è **COMPLETAMENTE SICURA**.",
        securityWarningText3: "I tuoi dati sono salvati SOLO sul tuo telefono e non lasciano MAI il dispositivo.",
        securityPoint1: "• **Dati 100% Locali:** Nessuna connessione a server esterni.",
        securityPoint2: "• **Nessuna Raccolta Dati:** La tua privacy è garantita.",
        securityPoint3: "• **Codice Aperto:** Codice trasparente e verificabile.",
        securityPoint4: "• **Contatto Diretto:** Per dubbi, contatta Guillermo Pérez (coachdeeper@gmail.com).",
        suggestionsTitle: "Invia Suggerimenti",
        suggestionsSubtitle: "La tua opinione è importante.",
        suggestionSubject: "Oggetto:",
        suggestionMessage: "Il tuo suggerimento:",
        sendSuggestion: "Invia Suggerimento",
        emailClientWillOpen: "Si aprirà il tuo client di posta.",
        aboutTitle: "Impostazioni e Copyright",
        copyrightText: "App di proprietà di Guillermo Pérez (CoachDeeper). Vietata la copia o distribuzione. Contatto: coachdeeper@gmail.com.",
        emailContact: "coachdeeper@gmail.com",
        itIsTimeToTakeMedication: "È ora di prendere la medicina!",
        accept: "Accetta",
        removeTime: "Rimuovi",
        howToUseHome: "Naviga tra 'Farmaci', 'Pressione' e 'Cronologia'.",
        howToUseMedications: "Aggiungi, modifica e segna i farmaci come assunti.",
        howToUseBloodPressure: "Registra le tue letture e visualizza il grafico dei progressi.",
        howToUseHistory: "Rivedi e esporta la tua cronologia di assunzioni e letture.",
        howToUseSuggestions: "Inviaci suggerimenti tramite il tuo client di posta.",
        howToUseAbout: "Info su copyright e opzioni di backup.",
        deleteMedication: "Elimina Farmaco",
        deleteReading: "Elimina Lettura",
        date: "Data",
        notes: "Note",
        dosesForToday: "Dosi di oggi:",
        noDosesForToday: "Nessuna dose programmata per oggi.",
        notificationsNotSupported: "Il tuo browser non supporta le notifiche.",
        notificationsDenied: "Hai negato i permessi di notifica. Abilitali nelle impostazioni del browser per i promemoria.",
        bpReminderTitle: "Promemoria Pressione",
        bpReminderBody: "È ora di misurare la tua pressione sanguigna.",
        backupAndRestore: "Backup e Ripristino",
        backupDescription: "Salva una copia di backup di tutti i tuoi dati. Puoi ripristinarla in seguito o su un altro dispositivo.",
        createBackup: "Crea Backup",
        restoreFromBackup: "Ripristina da Backup",
        backupSuccess: "Backup creato con successo!",
        backupFailed: "Errore durante la creazione del backup.",
        confirmRestore: "Sei sicuro di voler ripristinare? I dati attuali verranno sovrascritti.",
        restoreSuccess: "Dati ripristinati! L'app si ricaricherà.",
        restoreFailed: "Errore durante il ripristino. Il file potrebbe essere danneggiato.",
        restoreInvalidFile: "Il file di backup non è valido.",
        searchHistory: "Cerca nella cronologia...",
        noResultsFound: "Nessun risultato trovato.",
        guideWelcomeTitle: "Benvenuto/a in Salute Facile!",
        guideWelcomeText: "Questa guida ti aiuterà a ottenere il massimo dal tuo assistente sanitario personale. Tutte le tue informazioni sono private e salvate solo sul tuo dispositivo.",
        guideFeaturesTitle: "Funzionalità Principali",
        guideFeatureMeds: "**Gestione Farmaci:** Aggiungi tutti i tuoi farmaci, personalizza dosi, orari e frequenze. Segna ogni assunzione per non dimenticarne nessuna.",
        guideFeatureBP: "**Controllo Pressione:** Registra le tue letture di pressione (sistolica, diastolica) e pulsazioni. Visualizza i tuoi progressi con un grafico interattivo.",
        guideFeatureHistory: "**Cronologia Completa:** Consulta un registro di ogni farmaco assunto e lettura della pressione. Puoi cercare ed esportare la cronologia!",
        guideFeatureBackup: "**Backup:** Non perdere i tuoi dati. Da 'Impostazioni', crea un backup di tutte le tue informazioni e ripristinalo quando necessario.",
        guideExamplesTitle: "Esempi Pratici",
        guideExampleMedsTitle: "Caso 1: Terapia Giornaliera e Settimanale",
        guideExampleMedsText: "Immagina di dover prendere 'Farmaco A' ogni giorno alle 9:00 e 'Vitamina D' solo la domenica. Configurali entrambi in 'Farmaci'. L'app ti mostrerà ogni giorno cosa devi prendere.",
        guideExampleBPTitle: "Caso 2: Monitoraggio per il Medico",
        guideExampleBPText: "Il medico ti chiede di misurare la pressione due volte al giorno. Registra ogni lettura in 'Pressione'. Alla visita, mostra il grafico o esporta la cronologia per inviargliela.",
        guideProTipsTitle: "Consigli per Sfruttare al Meglio l'App",
        guideProTip1: "**Installa l'App:** Segui i passaggi per avere 'Salute Facile' sulla tua schermata iniziale. Funziona offline ed è più comodo.",
        guideProTip2: "**Attiva Promemoria:** Quando configuri un farmaco o una misurazione della pressione, imposta un orario per ricevere una notifica. È il modo più efficace per non dimenticare nulla.",
        guideProTip3: "**Usa le Note:** Quando registri una misurazione della pressione, ti sentivi stordito? Avevi fatto esercizio? Anno-talo in 'Note'. Sono informazioni preziose per te e per il tuo medico.",
        guideProTip4: "**Fai dei Backup:** Specialmente se cambi telefono. Vai su 'Impostazioni' e crea un backup di tanto in tanto. È la tua assicurazione dati!",
        analyzeWithAI: "Analizza con IA",
        aiAnalysisTitle: "Analisi IA",
        aiAnalysisLoading: "Analisi dei tuoi dati in corso...",
        aiAnalysisDisclaimer: "Questa è un'analisi generata da IA e non sostituisce il parere medico professionale.",
        aiAnalysisError: "Impossibile completare l'analisi. Riprova.",
        needMoreReadingsForAI: "Sono necessarie almeno 5 misurazioni per un'analisi significativa.",
    },
    en: {
        languageName: "English",
        home: "Home",
        medications: "Medications",
        bloodPressure: "Blood Pressure",
        history: "History",
        suggestions: "Suggestions",
        aboutApp: "Settings",
        howToUseApp: "User Guide",
        back: "Back",
        appTitle: "Easy Health",
        appSubtitle: "Your personal assistant for managing medications and blood pressure.",
        yourMedications: "Your Medications",
        addMedication: "Add Medication",
        editMedication: "Edit Medication",
        markAsTaken: "Mark as taken",
        medicationTaken: "Taken",
        noMedications: "No medications registered. Add one!",
        medicationName: "Medication Name:",
        dosage: "Dosage (e.g., 500mg, 1 pill):",
        frequency: "Frequency:",
        daily: "Daily",
        weekly: "Weekly",
        specificTime: "Specific times",
        withMeals: "With meals",
        mealTimes: "Meal time:",
        breakfast: "Breakfast",
        lunch: "Lunch",
        dinner: "Dinner",
        daysOfWeek: "Days of the week:",
        sunday: "Sunday",
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
        times: "Times:",
        addAnotherTime: "Add another time",
        saveMedication: "Save Medication",
        updateMedication: "Update Medication",
        cancel: "Cancel",
        bloodPressureLog: "Blood Pressure Log",
        addReading: "Add Reading",
        editReading: "Edit Reading",
        systolic: "Systolic (mmHg):",
        diastolic: "Diastolic (mmHg):",
        pulse: "Pulse (bpm):",
        notesOptional: "Notes (optional):",
        setReminder: "Set reminder for blood pressure:",
        reminderTime: "Reminder time:",
        reminderDays: "Reminder days:",
        saveReading: "Save Reading",
        updateReading: "Update Reading",
        bloodPressureChart: "Blood Pressure Chart",
        systolicShort: "Systolic",
        diastolicShort: "Diastolic",
        pulseShort: "Pulse",
        needMoreReadings: "You need at least 2 readings to see the chart.",
        noReadings: "No blood pressure readings. Add one!",
        fullHistory: "Full History",
        exportHistory: "Export History to CSV",
        noHistory: "No events in history.",
        medicationEvent: "Medication: {name} ({dosage}) - Taken",
        bpEvent: "BP: {systolic}/{diastolic} mmHg, Pulse: {pulse} bpm - {time}",
        confirmDeleteMedication: "Are you sure you want to delete this medication?",
        medicationDeleted: "Medication deleted.",
        confirmDeleteReading: "Are you sure you want to delete this reading?",
        readingDeleted: "Reading deleted.",
        fillAllFields: "Please fill in all required fields.",
        selectAtLeastOneDay: "Please select at least one day for weekly frequency.",
        enterAllTimes: "Please enter all times for specific frequency.",
        selectMealTime: "Please select at least one meal time.",
        medicationAddedSuccess: "Medication added successfully!",
        medicationUpdatedSuccess: "Medication updated successfully!",
        bpReadingAddedSuccess: "Blood pressure reading added successfully!",
        bpReadingUpdatedSuccess: "Blood pressure reading updated successfully!",
        dataLoadError: "Could not load saved data. The application has been reset.",
        exportSuccess: "History exported to easy_health_history.csv",
        installTitle: "Install the App on Your Phone (PWA)",
        installStep1: "1. Open the application link in your browser (Chrome, Safari, etc.).",
        installStep2: "2. Look for the 'Share' icon or your browser's menu (usually three dots).",
        installStep3: "3. Select the 'Add to Home Screen' or 'Install app' option.",
        installStep4: "4. Confirm the installation. The 'Easy Health' icon will appear on your home screen.",
        installStep5: "5. Done! You can now use the app like a native application.",
        securityWarningTitle: "Your Privacy is Our Priority!",
        securityWarningText1: "Your phone or browser may show warnings during installation. This is NORMAL for a 'Progressive Web App' (PWA) that doesn't come from an app store.",
        securityWarningText2: "We guarantee that the application is **COMPLETELY SAFE**.",
        securityWarningText3: "Your data is saved ONLY on your phone and NEVER leaves it.",
        securityPoint1: "• **100% Local Data:** The app does NOT connect to any external server. Your data is yours alone.",
        securityPoint2: "• **No Data Collection:** This app does not collect, store, or share any personal data.",
        securityPoint3: "• **Open Source:** The code is visible and auditable for full transparency.",
        securityPoint4: "• **Direct Contact:** For any questions, contact the developer: Guillermo Pérez (coachdeeper@gmail.com).",
        suggestionsTitle: "Send Your Suggestions",
        suggestionsSubtitle: "Your feedback is very important for improving the app.",
        suggestionSubject: "Subject:",
        suggestionMessage: "Your suggestion:",
        sendSuggestion: "Send Suggestion",
        emailClientWillOpen: "Your email client will open to send the suggestion.",
        aboutTitle: "Settings and Copyright",
        copyrightText: "This app is the intellectual property of Guillermo Pérez (CoachDeeper). Copying, modification, or distribution without express permission is prohibited. Contact: coachdeeper@gmail.com.",
        emailContact: "coachdeeper@gmail.com",
        itIsTimeToTakeMedication: "Time to take your medication!",
        accept: "Accept",
        removeTime: "Remove",
        howToUseHome: "Navigate to key sections: 'Medications', 'Blood Pressure', and 'History'.",
        howToUseMedications: "Add, edit, and mark your medications as taken. Set up custom doses and frequencies.",
        howToUseBloodPressure: "Log your blood pressure readings. The app will generate a visual chart to track your progress.",
        howToUseHistory: "Review a chronological summary of all your taken doses and readings. Export your history to CSV.",
        howToUseSuggestions: "Send us your suggestions for improving the application through your email client.",
        howToUseAbout: "Information about authorship, app rights, and backup options.",
        deleteMedication: "Delete Medication",
        deleteReading: "Delete Reading",
        date: "Date",
        notes: "Notes",
        dosesForToday: "Doses for today:",
        noDosesForToday: "No doses scheduled for today.",
        notificationsNotSupported: "Your browser does not support notifications.",
        notificationsDenied: "You have denied notification permissions. Please enable them in your browser settings if you want reminders.",
        bpReminderTitle: "Blood Pressure Reminder",
        bpReminderBody: "It's time to take your blood pressure reading.",
        backupAndRestore: "Backup and Restore",
        backupDescription: "Save a backup of all your data to a file. You can restore it later or on another device.",
        createBackup: "Create Backup",
        restoreFromBackup: "Restore from Backup",
        backupSuccess: "Backup created successfully!",
        backupFailed: "Failed to create backup.",
        confirmRestore: "Are you sure you want to restore? All current data will be overwritten.",
        restoreSuccess: "Data restored successfully! The app will now reload.",
        restoreFailed: "Failed to restore data. The file may be corrupt.",
        restoreInvalidFile: "The backup file is invalid.",
        searchHistory: "Search history...",
        noResultsFound: "No results found.",
        guideWelcomeTitle: "Welcome to Easy Health!",
        guideWelcomeText: "This guide will help you get the most out of your personal health assistant. All your information is private and stored only on your device.",
        guideFeaturesTitle: "Main Features",
        guideFeatureMeds: "**Medication Management:** Add all your medications, customize doses, schedules, and frequencies (daily, weekly, with meals). Check off each dose so you don't miss any.",
        guideFeatureBP: "**Blood Pressure Tracking:** Log your blood pressure (systolic, diastolic) and pulse readings. Visualize your progress with an interactive chart.",
        guideFeatureHistory: "**Complete History:** See a chronological record of every medication taken and every blood pressure reading. You can search and export your history!",
        guideFeatureBackup: "**Backups:** Don't lose your data. From 'Settings', you can create a backup of all your information and restore it whenever you need.",
        examplesTitle: "Practical Examples",
        guideExampleMedsTitle: "Case 1: Daily and Weekly Treatment",
        guideExampleMedsText: "Imagine you take 'Drug A' every day at 9:00 AM and 'Vitamin D' only on Sundays. Set up both in the 'Medications' section. The app will show you what's due each day, and you can mark it as 'Taken' to keep perfect track.",
        guideExampleBPTitle: "Case 2: Follow-up for the Doctor",
        guideExampleBPText: "Your doctor asks you to take your blood pressure twice a day. Log each reading in 'Blood Pressure'. At your appointment, you can show the interactive chart directly from your phone or use the 'Export' button in 'History' to email it.",
        guideProTipsTitle: "Tips to Get the Most Out of It",
        guideProTip1: "**Install the App:** Follow the installation steps to get 'Easy Health' on your home screen. It works offline and is more convenient.",
        guideProTip2: "**Enable Reminders:** When you set up a medication or blood pressure reading, set a time to receive a notification. It's the most effective way to remember everything.",
        guideProTip3: "**Use Notes:** When logging a blood pressure reading, did you feel dizzy? Had you exercised? Write it down in 'Notes'. It's valuable information for you and your doctor.",
        guideProTip4: "**Make Backups:** Especially if you're switching phones. Go to 'Settings' and create a backup from time to time. It's your data insurance!",
        analyzeWithAI: "Analyze with AI",
        aiAnalysisTitle: "AI Analysis",
        aiAnalysisLoading: "Analyzing your data...",
        aiAnalysisDisclaimer: "This is an AI-generated analysis and does not replace professional medical advice.",
        aiAnalysisError: "Could not complete the analysis. Please try again.",
        needMoreReadingsForAI: "At least 5 readings are needed for a meaningful analysis.",
    },
    de: {
        languageName: "Deutsch",
        home: "Start",
        medications: "Medikamente",
        bloodPressure: "Blutdruck",
        history: "Verlauf",
        suggestions: "Vorschläge",
        aboutApp: "Einstellungen",
        howToUseApp: "Anleitung",
        back: "Zurück",
        appTitle: "Einfache Gesundheit",
        appSubtitle: "Ihr persönlicher Assistent für Medikamente und Blutdruck.",
        yourMedications: "Ihre Medikamente",
        addMedication: "Medikament hinzufügen",
        editMedication: "Medikament bearbeiten",
        markAsTaken: "Als eingenommen markieren",
        medicationTaken: "Eingenommen",
        noMedications: "Keine Medikamente registriert. Fügen Sie eins hinzu!",
        medicationName: "Name des Medikaments:",
        dosage: "Dosis (z.B. 500mg, 1 Tablette):",
        frequency: "Häufigkeit:",
        daily: "Täglich",
        weekly: "Wöchentlich",
        specificTime: "Bestimmte Zeiten",
        withMeals: "Zu den Mahlzeiten",
        mealTimes: "Mahlzeit:",
        breakfast: "Frühstück",
        lunch: "Mittagessen",
        dinner: "Abendessen",
        daysOfWeek: "Wochentage:",
        sunday: "Sonntag",
        monday: "Montag",
        tuesday: "Dienstag",
        wednesday: "Mittwoch",
        thursday: "Donnerstag",
        friday: "Freitag",
        saturday: "Samstag",
        times: "Zeiten:",
        addAnotherTime: "Weitere Zeit hinzufügen",
        saveMedication: "Medikament speichern",
        updateMedication: "Medikament aktualisieren",
        cancel: "Abbrechen",
        bloodPressureLog: "Blutdruckprotokoll",
        addReading: "Messwert hinzufügen",
        editReading: "Messwert bearbeiten",
        systolic: "Systolisch (mmHg):",
        diastolic: "Diastolisch (mmHg):",
        pulse: "Puls (S/min):",
        notesOptional: "Notizen (optional):",
        setReminder: "Erinnerung für Blutdruckmessung:",
        reminderTime: "Erinnerungszeit:",
        reminderDays: "Erinnerungstage:",
        saveReading: "Messwert speichern",
        updateReading: "Messwert aktualisieren",
        bloodPressureChart: "Blutdruckdiagramm",
        systolicShort: "Systolisch",
        diastolicShort: "Diastolisch",
        pulseShort: "Puls",
        needMoreReadings: "Sie benötigen mindestens 2 Messwerte, um das Diagramm anzuzeigen.",
        noReadings: "Keine Blutdruckmesswerte. Fügen Sie einen hinzu!",
        fullHistory: "Vollständiger Verlauf",
        exportHistory: "Verlauf als CSV exportieren",
        noHistory: "Keine Ereignisse im Verlauf.",
        medicationEvent: "Medikament: {name} ({dosage}) - Eingenommen",
        bpEvent: "Blutdruck: {systolic}/{diastolic} mmHg, Puls: {pulse} S/min - {time}",
        confirmDeleteMedication: "Sind Sie sicher, dass Sie dieses Medikament löschen möchten?",
        medicationDeleted: "Medikament gelöscht.",
        confirmDeleteReading: "Sind Sie sicher, dass Sie diesen Messwert löschen möchten?",
        readingDeleted: "Messwert gelöscht.",
        fillAllFields: "Bitte füllen Sie alle Pflichtfelder aus.",
        selectAtLeastOneDay: "Bitte wählen Sie mindestens einen Tag für die wöchentliche Häufigkeit.",
        enterAllTimes: "Bitte geben Sie alle Zeiten für die spezifische Häufigkeit ein.",
        selectMealTime: "Bitte wählen Sie mindestens eine Mahlzeit aus.",
        medicationAddedSuccess: "Medikament erfolgreich hinzugefügt!",
        medicationUpdatedSuccess: "Medikament erfolgreich aktualisiert!",
        bpReadingAddedSuccess: "Blutdruckmesswert erfolgreich hinzugefügt!",
        bpReadingUpdatedSuccess: "Blutdruckmesswert erfolgreich aktualisiert!",
        dataLoadError: "Gespeicherte Daten konnten nicht geladen werden. Die Anwendung wurde zurückgesetzt.",
        exportSuccess: "Verlauf nach einfache_gesundheit_verlauf.csv exportiert",
        installTitle: "App auf Ihrem Handy installieren (PWA)",
        installStep1: "1. Öffnen Sie den Anwendungslink in Ihrem Browser (Chrome, Safari, etc.).",
        installStep2: "2. Suchen Sie das 'Teilen'-Symbol oder das Menü Ihres Browsers (normalerweise drei Punkte).",
        installStep3: "3. Wählen Sie die Option 'Zum Startbildschirm hinzufügen' oder 'App installieren'.",
        installStep4: "4. Bestätigen Sie die Installation. Das 'Einfache Gesundheit'-Symbol erscheint auf Ihrem Startbildschirm.",
        installStep5: "5. Fertig! Sie können die App jetzt wie eine native Anwendung verwenden.",
        securityWarningTitle: "Ihre Privatsphäre ist unsere Priorität!",
        securityWarningText1: "Ihr Telefon oder Browser zeigt möglicherweise Warnungen während der Installation an. Das ist NORMAL für eine 'Progressive Web App' (PWA), die nicht aus einem App-Store stammt.",
        securityWarningText2: "Wir garantieren, dass die Anwendung **VOLLSTÄNDIG SICHER** ist.",
        securityWarningText3: "Ihre Daten werden NUR auf Ihrem Telefon gespeichert und verlassen es NIEMALS.",
        securityPoint1: "• **100% lokale Daten:** Die App verbindet sich NICHT mit externen Servern. Ihre Daten gehören nur Ihnen.",
        securityPoint2: "• **Keine Datenerfassung:** Diese App sammelt, speichert oder teilt keine persönlichen Daten.",
        securityPoint3: "• **Open Source:** Der Code ist für volle Transparenz sichtbar und überprüfbar.",
        securityPoint4: "• **Direkter Kontakt:** Bei Fragen wenden Sie sich an den Entwickler: Guillermo Pérez (coachdeeper@gmail.com).",
        suggestionsTitle: "Senden Sie Ihre Vorschläge",
        suggestionsSubtitle: "Ihre Meinung ist sehr wichtig, um die App zu verbessern.",
        suggestionSubject: "Betreff:",
        suggestionMessage: "Ihr Vorschlag:",
        sendSuggestion: "Vorschlag senden",
        emailClientWillOpen: "Ihr E-Mail-Programm wird geöffnet, um den Vorschlag zu senden.",
        aboutTitle: "Einstellungen und Urheberrecht",
        copyrightText: "Diese App ist geistiges Eigentum von Guillermo Pérez (CoachDeeper). Kopieren, Ändern oder Verteilen ohne ausdrückliche Genehmigung ist verboten. Kontakt: coachdeeper@gmail.com.",
        emailContact: "coachdeeper@gmail.com",
        itIsTimeToTakeMedication: "Zeit, Ihr Medikament zu nehmen!",
        accept: "Akzeptieren",
        removeTime: "Entfernen",
        howToUseHome: "Navigieren Sie zu den Hauptbereichen: 'Medikamente', 'Blutdruck' und 'Verlauf'.",
        howToUseMedications: "Fügen Sie Ihre Medikamente hinzu, bearbeiten Sie sie und markieren Sie sie als eingenommen. Richten Sie benutzerdefinierte Dosen und Häufigkeiten ein.",
        howToUseBloodPressure: "Protokollieren Sie Ihre Blutdruckmesswerte. Die App erstellt ein visuelles Diagramm, um Ihren Fortschritt zu verfolgen.",
        howToUseHistory: "Überprüfen Sie eine chronologische Zusammenfassung all Ihrer eingenommenen Dosen und Messwerte. Exportieren Sie Ihren Verlauf als CSV.",
        howToUseSuggestions: "Senden Sie uns Ihre Vorschläge zur Verbesserung der Anwendung über Ihr E-Mail-Programm.",
        howToUseAbout: "Informationen über Urheberschaft, App-Rechte und Sicherungsoptionen.",
        deleteMedication: "Medikament löschen",
        deleteReading: "Messwert löschen",
        date: "Datum",
        notes: "Notizen",
        dosesForToday: "Dosen für heute:",
        noDosesForToday: "Keine Dosen für heute geplant.",
        notificationsNotSupported: "Ihr Browser unterstützt keine Benachrichtigungen.",
        notificationsDenied: "Sie haben Benachrichtigungsberechtigungen verweigert. Bitte aktivieren Sie sie in Ihren Browsereinstellungen, wenn Sie Erinnerungen wünschen.",
        bpReminderTitle: "Blutdruck-Erinnerung",
        bpReminderBody: "Es ist Zeit, Ihren Blutdruck zu messen.",
        backupAndRestore: "Sicherung und Wiederherstellung",
        backupDescription: "Speichern Sie eine Sicherung all Ihrer Daten in einer Datei. Sie können sie später oder auf einem anderen Gerät wiederherstellen.",
        createBackup: "Sicherung erstellen",
        restoreFromBackup: "Aus Sicherung wiederherstellen",
        backupSuccess: "Sicherung erfolgreich erstellt!",
        backupFailed: "Fehler beim Erstellen der Sicherung.",
        confirmRestore: "Sind Sie sicher, dass Sie wiederherstellen möchten? Alle aktuellen Daten werden überschrieben.",
        restoreSuccess: "Daten erfolgreich wiederhergestellt! Die App wird jetzt neu geladen.",
        restoreFailed: "Fehler beim Wiederherstellen der Daten. Die Datei ist möglicherweise beschädigt.",
        restoreInvalidFile: "Die Sicherungsdatei ist ungültig.",
        searchHistory: "Verlauf durchsuchen...",
        noResultsFound: "Keine Ergebnisse gefunden.",
        guideWelcomeTitle: "Willkommen bei Einfache Gesundheit!",
        guideWelcomeText: "Diese Anleitung hilft Ihnen, das Beste aus Ihrem persönlichen Gesundheitsassistenten herauszuholen. Alle Ihre Informationen sind privat und werden nur auf Ihrem Gerät gespeichert.",
        guideFeaturesTitle: "Hauptfunktionen",
        guideFeatureMeds: "**Medikamentenverwaltung:** Fügen Sie alle Ihre Medikamente hinzu, passen Sie Dosen, Zeitpläne und Häufigkeiten an (täglich, wöchentlich, zu den Mahlzeiten). Haken Sie jede Dosis ab, damit Sie keine vergessen.",
        guideFeatureBP: "**Blutdruckkontrolle:** Erfassen Sie Ihre Blutdruck- (systolisch, diastolisch) und Pulswerte. Visualisieren Sie Ihren Fortschritt mit einem interaktiven Diagramm.",
        guideFeatureHistory: "**Vollständiger Verlauf:** Sehen Sie sich eine chronologische Aufzeichnung jedes eingenommenen Medikaments und jedes Blutdruckmesswerts an. Sie können Ihren Verlauf durchsuchen und exportieren!",
        guideFeatureBackup: "**Sicherungen:** Verlieren Sie Ihre Daten nicht. Unter 'Einstellungen' können Sie eine Sicherung all Ihrer Informationen erstellen und bei Bedarf wiederherstellen.",
        guideExamplesTitle: "Praktische Beispiele",
        guideExampleMedsTitle: "Fall 1: Tägliche und wöchentliche Behandlung",
        guideExampleMedsText: "Stellen Sie sich vor, Sie nehmen 'Medikament A' täglich um 9:00 Uhr und 'Vitamin D' nur sonntags. Richten Sie beides im Bereich 'Medikamente' ein. Die App zeigt Ihnen jeden Tag, was fällig ist, und Sie können es als 'Eingenommen' markieren, um den Überblick zu behalten.",
        guideExampleBPTitle: "Fall 2: Nachverfolgung für den Arzt",
        guideExampleBPText: "Ihr Arzt bittet Sie, Ihren Blutdruck zweimal täglich zu messen. Erfassen Sie jede Messung unter 'Blutdruck'. Bei Ihrem Termin können Sie das interaktive Diagramm direkt von Ihrem Telefon zeigen oder die 'Exportieren'-Schaltfläche im 'Verlauf' verwenden, um es per E-Mail zu senden.",
        guideProTipsTitle: "Tipps, um das Beste aus der App herauszuholen",
        guideProTip1: "**Installieren Sie die App:** Befolgen Sie die Schritte, um 'Einfache Gesundheit' auf Ihren Startbildschirm zu bekommen. Sie funktioniert offline und ist bequemer.",
        guideProTip2: "**Aktivieren Sie Erinnerungen:** Wenn Sie ein Medikament oder eine Blutdruckmessung einrichten, stellen Sie eine Zeit ein, um eine Benachrichtigung zu erhalten. Das ist der effektivste Weg, um nichts zu vergessen.",
        guideProTip3: "**Nutzen Sie Notizen:** Fühlten Sie sich bei einer Messung schwindelig? Hatten Sie Sport getrieben? Schreiben Sie es in 'Notizen'. Das sind wertvolle Informationen für Sie und Ihren Arzt.",
        guideProTip4: "**Machen Sie Backups:** Besonders bei einem Telefonwechsel. Gehen Sie zu 'Einstellungen' und erstellen Sie von Zeit zu Zeit eine Sicherung. Das ist Ihre Datenversicherung!",
        analyzeWithAI: "Mit KI analysieren",
        aiAnalysisTitle: "KI-Analyse",
        aiAnalysisLoading: "Analysiere deine Daten...",
        aiAnalysisDisclaimer: "Dies ist eine KI-generierte Analyse und ersetzt keine professionelle medizinische Beratung.",
        aiAnalysisError: "Analyse konnte nicht abgeschlossen werden. Bitte versuche es erneut.",
        needMoreReadingsForAI: "Für eine aussagekräftige Analyse sind mindestens 5 Messwerte erforderlich.",
    },
};